train_params:
  shuffle: true
  model_name: "gdn"
  batch_size: 32
  n_epochs: 2
  val_size: 0.1
  init_lr: 0.001
  clean: "drop"
  log_dir: "output"
  n_workers: 0
  test_size: 0.1
  log_every_n_steps: 1
  interpolate_method: null
  weight_decay: 0
  eps: 0.00000001
  betas: [0.9, 0.99]
  monitor: "Loss/val"
  monitor_mode: "min"
  early_stop_patience: 20
  early_stop_delta: 0.0001
  save_top_k: 1
  down_len: 10

model_params:
  window_size: 255
  embed_dim: 128
  out_layer_num: 2
  out_layer_inter_dim: 10
  topk: 10
  heads: 2
  dropout: 0.4
  negative_slope: 0.2
  

env_params:
  save_path_pattern: ""
  random_seed: 42
  report: "best"
  load_model_path: ""
  save_path: "msl"

predictor_params:
  ckpt_folder: "output/gdn/version_5"
  n_thresholds: 1000
  window_size_smooth: 5
  post_process_scores: true
  score_type: "abs"
  dataset_for_threshold: "train"
  range_based: true


optimization_params:
  study_name: "gdn_optimization"
  n_trials: 100
  metric: "vus_roc_system"
