env_params:
  random_seed: 42

train_params:
  test_size: 0.1
  val_size: 0.1
  model_name: "gcn"
  clean: "drop"
  log_dir: "output"
  interpolate_method: null
  shuffle: true
  batch_size: 128
  n_workers: 0
  init_lr: 0.001
  n_epochs: 2 ####50
  log_every_n_steps: 1
  ckpt_path_resume: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  down_len: 10

model_params:
  window_size: 5
  n_layers: 9
  hidden_dim: 80
  K: 3

predictor_params:
  ckpt_folder: "output/gcn/version_6"
  n_thresholds: 100
  window_size_smooth: 5
  post_process_scores: true
  score_type: "abs"
  dataset_for_threshold: "train"
  range_based: true


optimization_params:
  study_name: "gcn_optimization"
  n_trials: 100
  metric: "vus_roc_system"
