model_params:
  window_size: 205
  n_layers: 1
  hidden_dim: 128
  K: 2

train_params:
  model_name: "gcn"
  log_dir: "benchmarks"
  n_epochs: 200
  batch_size: 512
  init_lr: 0.001
  target_dims: null
  n_workers: 0
  log_every_n_steps: 1
  shuffle: true
  clean: "drop"
  interpolate_method: null
  weight_decay: 0.00001
  eps: 0.00000001
  betas: [0.9, 0.999]
  horizon: 1
  down_len: 1  
  max_std: 7.0
  monitor: "Loss/val"
  monitor_mode: "min"
  early_stop_patience: 10
  early_stop_delta: 0.001

predictor_params:
  post_process_scores: true
  n_thresholds: 100
  window_size_smooth: 5 
  dataset_for_threshold: "train"
  range_based: true

  score_type: "abs"
  ckpt_folder: "output/gcn/version_1"
